/*
 * Tienda.java
 *
 * Generated with Matisse Schema Definition Language 9.1.11
 * Generation date: Wed Feb 20 18:38:40 2019
 */

// Note: the package and extends declarations are generated by mt_sdl, do not modify them

import com.matisse.reflect.*;

/**
 * <code>Tienda</code> is a schema class generated by <code>mt_sdl</code>.
 * Any user-written classes will be found at the end of the file, after
 * the '// END of Matisse SDL Generated Code' comment.
 * Attribute types, default values, and relationship minimum and maximum
 * cardinality are stored in the database itself, not in this source code.
 * For more information, see <i>Getting Started with MATISSE</i>.
 */
public class Tienda extends com.matisse.reflect.MtObject {

    // BEGIN Matisse SDL Generated Code
    // DO NOT MODIFY UNTIL THE 'END of Matisse SDL Generated Code' MARK BELOW
    /*
     * Generated with Matisse Schema Definition Language 9.1.11
     * Generation Date: Wed Feb 20 18:38:40 2019
     */

    /*
     * Class variables and methods
     */

    /** Class <code>Tienda</code> cache ID */
    private static int CID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtClass.Loader("Tienda"));

    /**
     * Gets the <code>Tienda</code> class descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a class descriptor
     */
    public static com.matisse.reflect.MtClass getClass(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtClass)db.getCachedObject(CID);
    }

    /**
     * Factory constructor. This constructor is called by <code>MtObjectFactory</code>.
     * It is public for technical reasons but is not intended to be called
     * directly by user methods.
     * @param db a database
     * @param mtOid an existing object ID in the database
     */
    public Tienda(com.matisse.MtDatabase db, int mtOid)  {
        super(db, mtOid);
    }

    /**
     * Cascaded constructor, used by subclasses to create a new object in the database.
     * It is protected for technical reasons but is not intended to be called
     * directly by user methods.
     * @param mtCls a class descriptor (the class to instantiate)
     */
    protected Tienda(com.matisse.reflect.MtClass mtCls)  {
        super(mtCls);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>instanceIterator(Tienda.class);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>instanceIterator(numObjPerBuffer, Tienda.class);
    }

    /**
     * Counts the number of instances of this class (and its subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getInstanceNumber();
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>ownInstanceIterator(Tienda.class);
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>ownInstanceIterator(numObjPerBuffer, Tienda.class);
    }

    /**
     * Counts the number of own instances of this class (excluding subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getOwnInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getOwnInstanceNumber();
    }

    /*
     * Attribute access methods
     */

    /* Attribute 'idTienda' */

    /** Attribute <code>idTienda</code> cache ID */
    private static int idTiendaCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("idTienda",CID));

    /**
     * Gets the <code>idTienda</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getIdTiendaAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(idTiendaCID);
    }


    /**
     * Gets the <code>idTienda</code> attribute value.
     * @return the value
     *
     * @see #setIdTienda
     * @see #removeIdTienda
     */
    public final int getIdTienda() {
        return getInteger(getIdTiendaAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>idTienda</code> attribute value.
     * @param val the new value
     *
     * @see #getIdTienda
     * @see #removeIdTienda
     */
    public final void setIdTienda(int val) {
        setInteger(getIdTiendaAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>idTienda</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getIdTienda
     * @see #setIdTienda
     */
    public final void removeIdTienda() {
        removeValue(getIdTiendaAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getIdTienda
     * @see #setIdTienda
     */
    public final boolean isIdTiendaDefaultValue() {
        return isDefaultValue(getIdTiendaAttribute(getMtDatabase()));
    }


    /* Attribute 'nombreTienda' */

    /** Attribute <code>nombreTienda</code> cache ID */
    private static int nombreTiendaCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("nombreTienda",CID));

    /**
     * Gets the <code>nombreTienda</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getNombreTiendaAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(nombreTiendaCID);
    }


    /**
     * Gets the <code>nombreTienda</code> attribute value.
     * @return the value
     *
     * @see #setNombreTienda
     * @see #removeNombreTienda
     */
    public final String getNombreTienda() {
        return getString(getNombreTiendaAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>nombreTienda</code> attribute value.
     * @param val the new value
     *
     * @see #getNombreTienda
     * @see #removeNombreTienda
     */
    public final void setNombreTienda(String val) {
        setString(getNombreTiendaAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>nombreTienda</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getNombreTienda
     * @see #setNombreTienda
     */
    public final void removeNombreTienda() {
        removeValue(getNombreTiendaAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getNombreTienda
     * @see #setNombreTienda
     */
    public final boolean isNombreTiendaDefaultValue() {
        return isDefaultValue(getNombreTiendaAttribute(getMtDatabase()));
    }


    /* Attribute 'ubicacion' */

    /** Attribute <code>ubicacion</code> cache ID */
    private static int ubicacionCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("ubicacion",CID));

    /**
     * Gets the <code>ubicacion</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getUbicacionAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(ubicacionCID);
    }


    /**
     * Gets the <code>ubicacion</code> attribute value.
     * @return the value
     *
     * @see #setUbicacion
     * @see #removeUbicacion
     */
    public final String getUbicacion() {
        return getString(getUbicacionAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>ubicacion</code> attribute value.
     * @param val the new value
     *
     * @see #getUbicacion
     * @see #removeUbicacion
     */
    public final void setUbicacion(String val) {
        setString(getUbicacionAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>ubicacion</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getUbicacion
     * @see #setUbicacion
     */
    public final void removeUbicacion() {
        removeValue(getUbicacionAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getUbicacion
     * @see #setUbicacion
     */
    public final boolean isUbicacionDefaultValue() {
        return isDefaultValue(getUbicacionAttribute(getMtDatabase()));
    }


    /*
     * Relationship access methods
     */

    /* Relationship 'es_vendido' */

    /** Relationship <code>es_vendido</code> cache ID */
    private static int es_vendidoCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtRelationship.Loader("es_vendido",CID));

    /**
     * Gets the <code>es_vendido</code> relationship descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a relationship descriptor object
     */
    public static com.matisse.reflect.MtRelationship getEs_vendidoRelationship(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtRelationship)db.getCachedObject(es_vendidoCID);
    }

    /**
     * Gets the <code>es_vendido</code> relationship's successors.
     * @return an array of objects
     *
     * @see #getEs_vendidoSize
     * @see #es_vendidoIterator
     * @see #setEs_vendido
     * @see #removeEs_vendido
     */
    public final Perfume[] getEs_vendido() {
        return (Perfume[])getSuccessors(getEs_vendidoRelationship(getMtDatabase()), Perfume.class);
    }

    /**
     * Counts the <code>es_vendido</code> relationship's successors.
     * @return the number of successors
     *
     * @see #getEs_vendido
     * @see #es_vendidoIterator
     * @see #setEs_vendido
     * @see #removeEs_vendido
     */
    public final int getEs_vendidoSize() {
        return getSuccessorSize(getEs_vendidoRelationship(getMtDatabase()));
    }

    /**
     * Opens an iterator on the <code>es_vendido</code> relationship's successors.
     * @param <E> a MtObject class     * @return an object iterator
     *
     * @see #getEs_vendido
     * @see #getEs_vendidoSize
     * @see #setEs_vendido
     * @see #removeEs_vendido
     */
    public final <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> es_vendidoIterator() {
        return this.<E>successorIterator(getEs_vendidoRelationship(getMtDatabase()), Perfume.class);
    }

    /**
     * Sets the <code>es_vendido</code> relationship's successors.
     * @param succs an array of objects
     *
     * @see #getEs_vendido
     * @see #getEs_vendidoSize
     * @see #es_vendidoIterator
     * @see #removeEs_vendido
     */
    public final void setEs_vendido(Perfume[] succs) {
        setSuccessors(getEs_vendidoRelationship(getMtDatabase()), succs);
    }

    /**
     * Inserts one object at the beginning of the existing <code>es_vendido</code> successors list.
     * @param succ the object to add
     *
     * @see #getEs_vendido
     * @see #getEs_vendidoSize
     * @see #es_vendidoIterator
     * @see #setEs_vendido
     * @see #removeEs_vendido
     */
    public final void prependEs_vendido(Perfume succ) {
        prependSuccessor(getEs_vendidoRelationship(getMtDatabase()), succ);
    }

    /**
     * Adds one object to the end of the existing <code>es_vendido</code> successors list.
     * @param succ the object to add
     *
     * @see #getEs_vendido
     * @see #setEs_vendido
     * @see #removeEs_vendido
     * @see #getEs_vendidoSize
     * @see #es_vendidoIterator
     */
    public final void appendEs_vendido(Perfume succ) {
        appendSuccessor(getEs_vendidoRelationship(getMtDatabase()), succ);
    }
    /** Adds multiple objects to the end of the existing <code>es_vendido</code> successors list.
     * @param succs an array of objects to add
     *
     * @see #getEs_vendido
     * @see #setEs_vendido
     * @see #removeEs_vendido
     * @see #getEs_vendidoSize
     * @see #es_vendidoIterator
     */
    public final void appendEs_vendido(Perfume[] succs) {
        addSuccessors(getEs_vendidoRelationship(getMtDatabase()), succs);
    }

    /**
     * Removes objects from the <code>es_vendido</code> successors list.
     * @param succs an array of objects to remove
     *
     * @see #getEs_vendido
     * @see #setEs_vendido
     * @see #getEs_vendidoSize
     * @see #es_vendidoIterator
     */
    public void removeEs_vendido(Perfume[] succs) {
        removeSuccessors(getEs_vendidoRelationship(getMtDatabase()), succs);
    }

    /**
     * Removes one object from the <code>es_vendido</code> successors list.
     * @param succ the object to remove
     *
     * @see #getEs_vendido
     * @see #setEs_vendido
     * @see #getEs_vendidoSize
     * @see #es_vendidoIterator
     */
    public void removeEs_vendido(Perfume succ) {
        removeSuccessor(getEs_vendidoRelationship(getMtDatabase()), succ);
    }

    /**
     * Removes all <code>es_vendido</code> successors.  When the minimum cardinality
     * is 1, a new successor must be set before commit.
     */
    public final void clearEs_vendido() {
        clearSuccessors(getEs_vendidoRelationship(getMtDatabase()));
    }


    // END of Matisse SDL Generated Code

    /*
     * You may add your own code here...
     */

    /**
     * Default constructor provided as an example.
     * You may delete this constructor or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @param db a database
     */
    public Tienda(com.matisse.MtDatabase db) {
        super(getClass(db));
    }

    /**
     * Example of <code>toString</code> method.
     * You may delete this method or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @return a string
     */
    public java.lang.String toString() {
        return super.toString() + "[Tienda]";
    }
}
