package Intefaz;

import Logica.ControlActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 *
 * @author MiguelAngel & Sergey
 */
public class Ventana extends javax.swing.JFrame {

    ControlActionListener control;

    /**
     * Constructor de la ventana
     */
    public Ventana() {
        initComponents();

        control = new ControlActionListener(this);

        //Poner botones a la escucha
        this.crearEsquema.addActionListener(control);
        this.insertarDatos.addActionListener(control);
        this.Procedimientos.addActionListener(control);
        this.modModulo_Alumno.addActionListener(control);
        this.verConsultas.addActionListener(control);
        this.ActualizacionesBorrado.addActionListener(control);
        this.Alumnos.addActionListener(control);
        this.Modulos.addActionListener(control);
        this.Profesores.addActionListener(control);
        this.introAlumnos.addActionListener(control);
        this.introModulos.addActionListener(control);
        this.introProfesores.addActionListener(control);
        this.insertarAltaAlumnos.addActionListener(control);
        this.insertarMatriculaAlumnos.addActionListener(control);
        this.altaAlumnos.addActionListener(control);
        this.matricular.addActionListener(control);
        this.listarNotas.addActionListener(control);
        this.listarProfesores.addActionListener(control);
        this.listarAlumnos.addActionListener(control);
        this.modAlumno.addActionListener(control);
        this.modModulo.addActionListener(control);
        this.eliminarAlumno.addActionListener(control);
        this.eliminarModulo.addActionListener(control);

        //A través de una clase anonima solo permito escribir dígitos en la nota
        this.notaAlumno.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();

                // Verifica si la tecla pulsada no es un dígito
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
                    e.consume();  // consume la letra
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IntroducirDatos = new javax.swing.JFrame();
        Alumnos = new javax.swing.JButton();
        Profesores = new javax.swing.JButton();
        Modulos = new javax.swing.JButton();
        IntroducirAlumnos = new javax.swing.JFrame();
        Expediente = new javax.swing.JLabel();
        NombreA = new javax.swing.JLabel();
        ApellidoPA = new javax.swing.JLabel();
        ApellidoMA = new javax.swing.JLabel();
        FechaNac = new javax.swing.JLabel();
        Delegado = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        introAlumnos = new javax.swing.JButton();
        IntroducirProfesores = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jTextField47 = new javax.swing.JTextField();
        jTextField48 = new javax.swing.JTextField();
        introProfesores = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jTextField51 = new javax.swing.JTextField();
        IntroducirModulos = new javax.swing.JFrame();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField52 = new javax.swing.JTextField();
        jTextField53 = new javax.swing.JTextField();
        jTextField55 = new javax.swing.JTextField();
        jTextField56 = new javax.swing.JTextField();
        introModulos = new javax.swing.JButton();
        ProcedimientosAlmacenados = new javax.swing.JFrame();
        altaAlumnos = new javax.swing.JButton();
        AlumnosIntroducidos = new javax.swing.JLabel();
        RespuestaAltaAlumnos = new javax.swing.JTextField();
        MAlumno = new javax.swing.JLabel();
        Alumno = new javax.swing.JLabel();
        listaAlumnos = new javax.swing.JComboBox();
        Modulo = new javax.swing.JLabel();
        listaModulos = new javax.swing.JComboBox();
        matricular = new javax.swing.JButton();
        insertarAltaAlumnos = new javax.swing.JButton();
        insertarMatriculaAlumnos = new javax.swing.JButton();
        consultas = new javax.swing.JFrame();
        listarNotas = new javax.swing.JButton();
        notasModulo = new javax.swing.JComboBox();
        listarProfesores = new javax.swing.JButton();
        profesorAlumno = new javax.swing.JComboBox();
        RConsulta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RespuestaConsulta = new javax.swing.JTextArea();
        alumnoModulo = new javax.swing.JComboBox();
        listarAlumnos = new javax.swing.JButton();
        ActualizarBorrar = new javax.swing.JFrame();
        alumnoMB = new javax.swing.JComboBox();
        eliminarAlumno = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        nombreAlumno = new javax.swing.JTextField();
        Nombre = new javax.swing.JLabel();
        condDelegado = new javax.swing.JComboBox();
        modAlumno = new javax.swing.JButton();
        moduloMB = new javax.swing.JComboBox();
        eliminarModulo = new javax.swing.JButton();
        cambiarNota = new javax.swing.JLabel();
        notaAlumno = new javax.swing.JTextField();
        modModulo = new javax.swing.JButton();
        imgBasedDatos = new javax.swing.JLabel();
        crearEsquema = new javax.swing.JButton();
        insertarDatos = new javax.swing.JButton();
        Procedimientos = new javax.swing.JButton();
        modModulo_Alumno = new javax.swing.JButton();
        Gestion = new javax.swing.JLabel();
        verConsultas = new javax.swing.JButton();
        ActualizacionesBorrado = new javax.swing.JButton();

        IntroducirDatos.setTitle("Introducir Datos");
        IntroducirDatos.setBounds(new java.awt.Rectangle(0, 0, 235, 160));

        Alumnos.setText("Insertar Alumnos Obligatorios");

        Profesores.setText("Insertar Profesores Obligatorios");

        Modulos.setText("Insertar Modulos Obligatorios");

        javax.swing.GroupLayout IntroducirDatosLayout = new javax.swing.GroupLayout(IntroducirDatos.getContentPane());
        IntroducirDatos.getContentPane().setLayout(IntroducirDatosLayout);
        IntroducirDatosLayout.setHorizontalGroup(
            IntroducirDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntroducirDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IntroducirDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IntroducirDatosLayout.createSequentialGroup()
                        .addComponent(Modulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addComponent(Alumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Profesores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        IntroducirDatosLayout.setVerticalGroup(
            IntroducirDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntroducirDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Modulos)
                .addGap(11, 11, 11)
                .addComponent(Alumnos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Profesores)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        IntroducirAlumnos.setTitle("Introducir Alumnos");
        IntroducirAlumnos.setBounds(new java.awt.Rectangle(0, 0, 445, 265));
        IntroducirAlumnos.setResizable(false);

        Expediente.setText("Expediente");

        NombreA.setText("Nombre");

        ApellidoPA.setText("ApellidoP");

        ApellidoMA.setText("ApellidoM");

        FechaNac.setText("FechaNac");

        Delegado.setText("Delegado");

        jTextField2.setEditable(false);
        jTextField2.setText("1");

        jTextField3.setEditable(false);
        jTextField3.setText("2");

        jTextField4.setEditable(false);
        jTextField4.setText("3");

        jTextField5.setEditable(false);
        jTextField5.setText("4");

        jTextField6.setEditable(false);
        jTextField6.setText("Miguel");

        jTextField7.setEditable(false);
        jTextField7.setText("Sergey");

        jTextField8.setEditable(false);
        jTextField8.setText("Julian");

        jTextField9.setEditable(false);
        jTextField9.setText("Juan");

        jTextField10.setEditable(false);
        jTextField10.setText("López");

        jTextField11.setEditable(false);
        jTextField11.setText("Sánchez");

        jTextField12.setEditable(false);
        jTextField12.setText("1996-09-06");

        jTextField13.setEditable(false);
        jTextField13.setText("False");

        jTextField14.setEditable(false);
        jTextField14.setText("Shevchenko");

        jTextField15.setEditable(false);
        jTextField15.setText("Rodrigo");

        jTextField16.setEditable(false);
        jTextField16.setText("González");

        jTextField17.setEditable(false);

        jTextField18.setEditable(false);
        jTextField18.setText("Jiménez");

        jTextField19.setEditable(false);
        jTextField19.setText("Martín");

        jTextField20.setEditable(false);
        jTextField20.setText("1996-02-15");
        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });

        jTextField21.setEditable(false);
        jTextField21.setText("1992-01-22");

        jTextField22.setEditable(false);
        jTextField22.setText("1998-05-05");

        jTextField23.setEditable(false);
        jTextField23.setText("False");

        jTextField24.setEditable(false);
        jTextField24.setText("False");

        jTextField25.setEditable(false);
        jTextField25.setText("True");

        introAlumnos.setText("Introducir Datos");

        javax.swing.GroupLayout IntroducirAlumnosLayout = new javax.swing.GroupLayout(IntroducirAlumnos.getContentPane());
        IntroducirAlumnos.getContentPane().setLayout(IntroducirAlumnosLayout);
        IntroducirAlumnosLayout.setHorizontalGroup(
            IntroducirAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntroducirAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IntroducirAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IntroducirAlumnosLayout.createSequentialGroup()
                        .addGroup(IntroducirAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField5)
                            .addComponent(jTextField4)
                            .addComponent(jTextField3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Expediente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(IntroducirAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(NombreA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(IntroducirAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ApellidoPA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField10)
                            .addComponent(jTextField14)
                            .addComponent(jTextField15)
                            .addComponent(jTextField16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(IntroducirAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(IntroducirAlumnosLayout.createSequentialGroup()
                                .addGroup(IntroducirAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField19, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                    .addComponent(jTextField17, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(IntroducirAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(IntroducirAlumnosLayout.createSequentialGroup()
                                        .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField23, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                                    .addGroup(IntroducirAlumnosLayout.createSequentialGroup()
                                        .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField25))
                                    .addGroup(IntroducirAlumnosLayout.createSequentialGroup()
                                        .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField24)))
                                .addGap(12, 12, 12))
                            .addGroup(IntroducirAlumnosLayout.createSequentialGroup()
                                .addGroup(IntroducirAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(IntroducirAlumnosLayout.createSequentialGroup()
                                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(IntroducirAlumnosLayout.createSequentialGroup()
                                        .addComponent(ApellidoMA)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(FechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(IntroducirAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(IntroducirAlumnosLayout.createSequentialGroup()
                                        .addComponent(Delegado)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(IntroducirAlumnosLayout.createSequentialGroup()
                                        .addComponent(jTextField13)
                                        .addContainerGap())))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IntroducirAlumnosLayout.createSequentialGroup()
                        .addComponent(introAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        IntroducirAlumnosLayout.setVerticalGroup(
            IntroducirAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntroducirAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IntroducirAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Expediente)
                    .addComponent(NombreA)
                    .addComponent(ApellidoPA)
                    .addComponent(ApellidoMA)
                    .addComponent(FechaNac)
                    .addComponent(Delegado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IntroducirAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(IntroducirAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(IntroducirAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(IntroducirAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(introAlumnos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        IntroducirProfesores.setTitle("Introducir Profesores");
        IntroducirProfesores.setBounds(new java.awt.Rectangle(0, 0, 600, 220));

        jLabel9.setText("RFC");

        jLabel10.setText("Nombre");

        jLabel11.setText("ApellidoP");

        jLabel12.setText("ApellidoM");

        jLabel13.setText("Direccion");

        jLabel14.setText("Telefono");

        jTextField26.setEditable(false);
        jTextField26.setText("1");

        jTextField27.setEditable(false);
        jTextField27.setText("2");

        jTextField28.setEditable(false);
        jTextField28.setText("3");

        jTextField30.setEditable(false);
        jTextField30.setText("Francisco Javier");

        jTextField31.setEditable(false);
        jTextField31.setText("Juan Miguel");

        jTextField32.setEditable(false);
        jTextField32.setText("Francisco");

        jTextField34.setEditable(false);
        jTextField34.setText("Fernández-Arévalo");

        jTextField35.setEditable(false);
        jTextField35.setText("Collado");

        jTextField36.setEditable(false);
        jTextField36.setText("Almería");

        jTextField37.setEditable(false);
        jTextField37.setText("654895578");

        jTextField38.setEditable(false);
        jTextField38.setText("Jiménez");

        jTextField39.setEditable(false);
        jTextField39.setText("Fernández de Piñar");

        jTextField41.setEditable(false);
        jTextField41.setText("Lechuga");

        jTextField42.setEditable(false);
        jTextField42.setText("López");

        jTextField44.setEditable(false);
        jTextField44.setText("Almería");
        jTextField44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField44ActionPerformed(evt);
            }
        });

        jTextField45.setEditable(false);
        jTextField45.setText("Almería");

        jTextField47.setEditable(false);
        jTextField47.setText("65488497");

        jTextField48.setEditable(false);
        jTextField48.setText("654782545");

        introProfesores.setText("Introducir Datos");

        jLabel15.setText("Codigo_modulo");

        jTextField1.setEditable(false);
        jTextField1.setText("2");

        jTextField50.setEditable(false);
        jTextField50.setText("2");

        jTextField51.setEditable(false);
        jTextField51.setText("1");

        javax.swing.GroupLayout IntroducirProfesoresLayout = new javax.swing.GroupLayout(IntroducirProfesores.getContentPane());
        IntroducirProfesores.getContentPane().setLayout(IntroducirProfesoresLayout);
        IntroducirProfesoresLayout.setHorizontalGroup(
            IntroducirProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntroducirProfesoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IntroducirProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IntroducirProfesoresLayout.createSequentialGroup()
                        .addGroup(IntroducirProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField28)
                            .addComponent(jTextField27)
                            .addComponent(jTextField26, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(IntroducirProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(IntroducirProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                .addComponent(jTextField32, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(IntroducirProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(IntroducirProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField34, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addComponent(jTextField38))
                            .addComponent(jTextField39, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(IntroducirProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(IntroducirProfesoresLayout.createSequentialGroup()
                                .addGroup(IntroducirProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField35)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(IntroducirProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField45)
                                    .addComponent(jTextField44, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField36, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)))
                            .addGroup(IntroducirProfesoresLayout.createSequentialGroup()
                                .addGroup(IntroducirProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField41, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                    .addComponent(jTextField42))
                                .addGap(71, 71, 71)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(IntroducirProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField47)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField37, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(jTextField48))
                        .addGap(18, 18, 18)
                        .addGroup(IntroducirProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1)
                            .addComponent(jTextField50)
                            .addComponent(jTextField51))
                        .addGap(4, 4, 4))
                    .addComponent(introProfesores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        IntroducirProfesoresLayout.setVerticalGroup(
            IntroducirProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntroducirProfesoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IntroducirProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IntroducirProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IntroducirProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(IntroducirProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(IntroducirProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(introProfesores)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        IntroducirModulos.setTitle("Insertar Modulos");
        IntroducirModulos.setBounds(new java.awt.Rectangle(0, 0, 180, 180));

        jLabel16.setText("Codigo");

        jLabel17.setText("Nombre");

        jTextField52.setEditable(false);
        jTextField52.setText("1");

        jTextField53.setEditable(false);
        jTextField53.setText("2");

        jTextField55.setEditable(false);
        jTextField55.setText("ACDAT");

        jTextField56.setEditable(false);
        jTextField56.setText("PSP");

        introModulos.setText("Introducir Datos");

        javax.swing.GroupLayout IntroducirModulosLayout = new javax.swing.GroupLayout(IntroducirModulos.getContentPane());
        IntroducirModulos.getContentPane().setLayout(IntroducirModulosLayout);
        IntroducirModulosLayout.setHorizontalGroup(
            IntroducirModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntroducirModulosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IntroducirModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IntroducirModulosLayout.createSequentialGroup()
                        .addGroup(IntroducirModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField53)
                            .addComponent(jTextField52, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(IntroducirModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField56, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(jTextField55))
                        .addGap(12, 34, Short.MAX_VALUE))
                    .addComponent(introModulos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        IntroducirModulosLayout.setVerticalGroup(
            IntroducirModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntroducirModulosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IntroducirModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IntroducirModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(IntroducirModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(introModulos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ProcedimientosAlmacenados.setBounds(new java.awt.Rectangle(0, 0, 500, 280));

        altaAlumnos.setText("Alumnos dados de Alta");

        AlumnosIntroducidos.setText("Ver cuantos alumnos se han introducido.");

        RespuestaAltaAlumnos.setEditable(false);
        RespuestaAltaAlumnos.setText("X alumnos introducidos.");

        MAlumno.setText("Matricular un alumno.");

        Alumno.setText("Alumno:");

        Modulo.setText("Modulo:");

        matricular.setText("Matricular Alumno");

        insertarAltaAlumnos.setText("Insertar Procedimiento altaAlumnos");

        insertarMatriculaAlumnos.setText("Insertar Procedimiento MatricularAlumnos");

        javax.swing.GroupLayout ProcedimientosAlmacenadosLayout = new javax.swing.GroupLayout(ProcedimientosAlmacenados.getContentPane());
        ProcedimientosAlmacenados.getContentPane().setLayout(ProcedimientosAlmacenadosLayout);
        ProcedimientosAlmacenadosLayout.setHorizontalGroup(
            ProcedimientosAlmacenadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProcedimientosAlmacenadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProcedimientosAlmacenadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insertarAltaAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(matricular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ProcedimientosAlmacenadosLayout.createSequentialGroup()
                        .addGroup(ProcedimientosAlmacenadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(altaAlumnos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ProcedimientosAlmacenadosLayout.createSequentialGroup()
                                .addComponent(Alumno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listaAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ProcedimientosAlmacenadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProcedimientosAlmacenadosLayout.createSequentialGroup()
                                .addComponent(Modulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(listaModulos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(RespuestaAltaAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)))
                    .addGroup(ProcedimientosAlmacenadosLayout.createSequentialGroup()
                        .addGroup(ProcedimientosAlmacenadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AlumnosIntroducidos)
                            .addComponent(MAlumno))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(insertarMatriculaAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ProcedimientosAlmacenadosLayout.setVerticalGroup(
            ProcedimientosAlmacenadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProcedimientosAlmacenadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insertarAltaAlumnos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(insertarMatriculaAlumnos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AlumnosIntroducidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProcedimientosAlmacenadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(altaAlumnos)
                    .addComponent(RespuestaAltaAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MAlumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProcedimientosAlmacenadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alumno)
                    .addComponent(listaAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Modulo)
                    .addComponent(listaModulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(matricular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        consultas.setBounds(new java.awt.Rectangle(0, 0, 500, 300));

        listarNotas.setText("Listado de Notas del Modulo Seleccionado");

        listarProfesores.setText("Listado de Profesores del Alumno Seleccionado");

        RConsulta.setText("Respuesta de la consulta:");

        RespuestaConsulta.setEditable(false);
        RespuestaConsulta.setColumns(20);
        RespuestaConsulta.setRows(5);
        jScrollPane1.setViewportView(RespuestaConsulta);

        listarAlumnos.setText("Listado de Alumnos del Modulo Seleccionado");

        javax.swing.GroupLayout consultasLayout = new javax.swing.GroupLayout(consultas.getContentPane());
        consultas.getContentPane().setLayout(consultasLayout);
        consultasLayout.setHorizontalGroup(
            consultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consultasLayout.createSequentialGroup()
                        .addComponent(RConsulta)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultasLayout.createSequentialGroup()
                        .addGroup(consultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, consultasLayout.createSequentialGroup()
                                .addGroup(consultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(listarNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(listarProfesores, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                                    .addComponent(listarAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(consultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(notasModulo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(profesorAlumno, 0, 100, Short.MAX_VALUE)
                                    .addComponent(alumnoModulo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(14, 14, 14))))
        );
        consultasLayout.setVerticalGroup(
            consultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listarNotas)
                    .addComponent(notasModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(consultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listarProfesores)
                    .addComponent(profesorAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(consultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alumnoModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listarAlumnos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ActualizarBorrar.setBounds(new java.awt.Rectangle(0, 0, 340, 250));

        eliminarAlumno.setText("Eliminar Alumno");

        jLabel8.setText("Nombre:");

        nombreAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreAlumnoActionPerformed(evt);
            }
        });

        Nombre.setText("Delegado");

        condDelegado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "True", "False" }));
        condDelegado.setSelectedIndex(1);

        modAlumno.setText("Modificar Alumno");

        eliminarModulo.setText("Eliminar Modulo");

        cambiarNota.setText("Cambiar Nota del Alumno Seleccionado:");

        notaAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notaAlumnoActionPerformed(evt);
            }
        });

        modModulo.setText("Modificar Modulo");

        javax.swing.GroupLayout ActualizarBorrarLayout = new javax.swing.GroupLayout(ActualizarBorrar.getContentPane());
        ActualizarBorrar.getContentPane().setLayout(ActualizarBorrarLayout);
        ActualizarBorrarLayout.setHorizontalGroup(
            ActualizarBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActualizarBorrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ActualizarBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ActualizarBorrarLayout.createSequentialGroup()
                        .addComponent(notaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modModulo, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                    .addGroup(ActualizarBorrarLayout.createSequentialGroup()
                        .addGroup(ActualizarBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ActualizarBorrarLayout.createSequentialGroup()
                                .addGroup(ActualizarBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ActualizarBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(moduloMB, 0, 89, Short.MAX_VALUE)
                                        .addComponent(alumnoMB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nombreAlumno))
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ActualizarBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Nombre)
                                    .addGroup(ActualizarBorrarLayout.createSequentialGroup()
                                        .addComponent(condDelegado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(modAlumno))
                                    .addComponent(eliminarModulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(eliminarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(cambiarNota))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(52, 52, 52))
        );
        ActualizarBorrarLayout.setVerticalGroup(
            ActualizarBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActualizarBorrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ActualizarBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alumnoMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarAlumno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ActualizarBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ActualizarBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(condDelegado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modAlumno))
                .addGap(18, 18, 18)
                .addGroup(ActualizarBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moduloMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarModulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cambiarNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ActualizarBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modModulo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Base De Datos Instituto");

        imgBasedDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bdEsquema.PNG"))); // NOI18N

        crearEsquema.setText("Crear el Esquema");
        crearEsquema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearEsquemaActionPerformed(evt);
            }
        });

        insertarDatos.setText("Insertar Datos en las Tablas");

        Procedimientos.setText("Procedimientos Almacenados");
        Procedimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcedimientosActionPerformed(evt);
            }
        });

        modModulo_Alumno.setText("Modificar la tabla Modulo_Alumno");

        Gestion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Gestion.setText("Gestionar:");

        verConsultas.setText("Consultas");

        ActualizacionesBorrado.setText("Actualizaciones o Borrado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgBasedDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Gestion)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(modModulo_Alumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Procedimientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(verConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ActualizacionesBorrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(insertarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(crearEsquema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgBasedDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(Gestion)
                        .addGap(35, 35, 35)
                        .addComponent(crearEsquema)
                        .addGap(26, 26, 26)
                        .addComponent(insertarDatos)
                        .addGap(32, 32, 32)
                        .addComponent(Procedimientos)
                        .addGap(32, 32, 32)
                        .addComponent(modModulo_Alumno)
                        .addGap(34, 34, 34)
                        .addComponent(verConsultas)
                        .addGap(34, 34, 34)
                        .addComponent(ActualizacionesBorrado)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearEsquemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearEsquemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearEsquemaActionPerformed

    private void ProcedimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcedimientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProcedimientosActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField44ActionPerformed

    private void nombreAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreAlumnoActionPerformed

    private void notaAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notaAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ActualizacionesBorrado;
    public javax.swing.JFrame ActualizarBorrar;
    private javax.swing.JLabel Alumno;
    public javax.swing.JButton Alumnos;
    private javax.swing.JLabel AlumnosIntroducidos;
    private javax.swing.JLabel ApellidoMA;
    private javax.swing.JLabel ApellidoPA;
    private javax.swing.JLabel Delegado;
    private javax.swing.JLabel Expediente;
    private javax.swing.JLabel FechaNac;
    private javax.swing.JLabel Gestion;
    public javax.swing.JFrame IntroducirAlumnos;
    public javax.swing.JFrame IntroducirDatos;
    public javax.swing.JFrame IntroducirModulos;
    public javax.swing.JFrame IntroducirProfesores;
    private javax.swing.JLabel MAlumno;
    private javax.swing.JLabel Modulo;
    public javax.swing.JButton Modulos;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel NombreA;
    public javax.swing.JButton Procedimientos;
    public javax.swing.JFrame ProcedimientosAlmacenados;
    public javax.swing.JButton Profesores;
    private javax.swing.JLabel RConsulta;
    public javax.swing.JTextField RespuestaAltaAlumnos;
    public javax.swing.JTextArea RespuestaConsulta;
    public javax.swing.JButton altaAlumnos;
    public javax.swing.JComboBox alumnoMB;
    public javax.swing.JComboBox alumnoModulo;
    private javax.swing.JLabel cambiarNota;
    public javax.swing.JComboBox condDelegado;
    public javax.swing.JFrame consultas;
    public javax.swing.JButton crearEsquema;
    public javax.swing.JButton eliminarAlumno;
    public javax.swing.JButton eliminarModulo;
    private javax.swing.JLabel imgBasedDatos;
    public javax.swing.JButton insertarAltaAlumnos;
    public javax.swing.JButton insertarDatos;
    public javax.swing.JButton insertarMatriculaAlumnos;
    public javax.swing.JButton introAlumnos;
    public javax.swing.JButton introModulos;
    public javax.swing.JButton introProfesores;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JTextField jTextField56;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    public javax.swing.JComboBox listaAlumnos;
    public javax.swing.JComboBox listaModulos;
    public javax.swing.JButton listarAlumnos;
    public javax.swing.JButton listarNotas;
    public javax.swing.JButton listarProfesores;
    public javax.swing.JButton matricular;
    public javax.swing.JButton modAlumno;
    public javax.swing.JButton modModulo;
    public javax.swing.JButton modModulo_Alumno;
    public javax.swing.JComboBox moduloMB;
    public javax.swing.JTextField nombreAlumno;
    public javax.swing.JTextField notaAlumno;
    public javax.swing.JComboBox notasModulo;
    public javax.swing.JComboBox profesorAlumno;
    public javax.swing.JButton verConsultas;
    // End of variables declaration//GEN-END:variables
}
